name: Python linters and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          # picologging does not support 3.13 yet
          # - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
        # Install a specific version of uv.
          version: "0.7.3"
          python-version: ${{ matrix.python-version }}
      - name: Run linters
        run: |
          uv run ruff format .
          uv run ruff check . --fix
          uv run flake8 . --select=WPS
          uv run mypy .
      - name: Run tests
        # Do not run coverage in CI for now
        run: uv run pytest tests --no-cov
  
